version: '3.8'

services:
  # Book Catalog Microservice
  book_catalog:
    build: ./book_catalog
    environment:
      DATABASE_URL: postgresql://my_database_winf_user:5ym89SWIq13xCBJuq8AEmdgQ9hJ97f23@dpg-crr9qbqj1k6c73ec3jp0-a.oregon-postgres.render.com/my_database_winf
    ports:
      - "8000:8000"

  # Inventory Management Microservice
  inventory_management:
    build: ./inventory_management
    environment:
      DATABASE_URL: postgresql://my_database_winf_user:5ym89SWIq13xCBJuq8AEmdgQ9hJ97f23@dpg-crr9qbqj1k6c73ec3jp0-a.oregon-postgres.render.com/my_database_winf
    ports:
      - "8001:8000"
