name: Terraform Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy to AKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    # Set up Terraform CLI
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    # Install Azure CLI and log in
    - name: Azure CLI Login
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az login --service-principal \
            --username ${{ secrets.ARM_CLIENT_ID }} \
            --password ${{ secrets.ARM_CLIENT_SECRET }} \
            --tenant ${{ secrets.ARM_TENANT_ID }}

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init
      working-directory: ./9.2D-resources/Terraform

    # Terraform Plan
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./9.2D-resources/Terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    # Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./9.2D-resources/Terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      # Run docker-compose to build and bring up the services
    - name: Build and run services with Docker Compose
      run: |
        docker-compose -f ./9.2D-resources/docker-compose.yml up --build -d

    # Login to Azure Container Registry
    - name: Azure ACR Login
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login myacrregistry123.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

    # Push Docker Image to ACR
    - name: Push Docker image
      run: docker push myacrregistry123.azurecr.io/book-catalog:latest

    # Apply Kubernetes Manifest
    - name: Apply Kubernetes Manifest
      run: |
        kubectl apply -f k8s/book-catalog-deployment.yaml
        kubectl apply -f k8s/book-catalog-service.yaml
      env:
        KUBECONFIG: ${{ steps.terraform.outputs.kube_config }}
